export const FETCH_USERS = 'FETCH_USERS';
export const NEW_USER = 'NEW_USER';
export const DOUBLE_MONEY = 'DOUBLE_MONEY';
export const WEALTH_GREATER_THAN_100 = 'WEALTH_GREATER_THAN_100';
export const SORT_BY_RICHEST = 'SORT_BY_RICHEST';
export const CALCULATE_TOTAL_WEALTH = 'CALCULATE_TOTAL_WEALTH';